# Generated by Django 4.2.2 on 2025-03-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("communication", "0002_alter_communication_links"),
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="client",
            field=models.ManyToManyField(to="client.client", verbose_name="Клиенты"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="communication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="communication.communication",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Окончание рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
