# Generated by Django 4.2.2 on 2025-03-14 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_client_alter_mailing_communication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Дата создания продукта",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего изменения продукта",
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
