# Generated by Django 4.2.2 on 2025-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='links',
            field=models.TextField(help_text='Добавьте текст сообщения', verbose_name='Текст сообщения'),
        ),
    ]
